api/src/main/java/org/jboss/pnc/dingrogu/api/client/AuthorizationClientHttpFactory.java, api/src/main/java/org/jboss/pnc/dingrogu/api/client/KonfluxBuildDriver.java, api/src/main/java/org/jboss/pnc/dingrogu/api/client/KonfluxBuildDriverProducer.java, api/src/main/java/org/jboss/pnc/dingrogu/api/client/RexProducer.java, pom.xml
Special thanks to @tecarter94 for his work on the konflux build driverclient which is what we are using for this! https://github.com/tecarter94/konflux-build-driver-client
=> Integration of the konflux build driver client

rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/KonfluxBuildDriverAdapter.java
=> Skip casting to ServerResponse for KonfluxBuildDriver

api/src/main/java/org/jboss/pnc/dingrogu/api/client/BuildDriver.java, api/src/main/java/org/jboss/pnc/dingrogu/api/client/BuildDriverProducer.java, api/src/main/java/org/jboss/pnc/dingrogu/api/client/EnvironmentDriver.java, api/src/main/java/org/jboss/pnc/dingrogu/api/client/EnvironmentDriverProducer.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/KonfluxBuildDriverAdapter.java
Client code for initial implementation of Dingrogu build process using PNC build backend.
https://issues.redhat.com/browse/NCL-9004
=> NCL-9004 Update Orch to support PNC builds via Dingrogu (client code)

rest-workflow/src/main/java/org/jboss/pnc/dingrogu/restworkflow/workflows/BuildWorkflow.java
Workflow code for initial implementation of Dingrogu build process using PNC build backend.
https://issues.redhat.com/browse/NCL-9004
=> NCL-9004 Update Orch to support PNC builds via Dingrogu (workflow code)

rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/BuildDriverAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/EnvironmentDriverCompleteAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/EnvironmentDriverCreateAdapter.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/BuildDriverAdapterTest.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/EnvironmentDriverCompleteAdapterTest.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/EnvironmentDriverCreateAdapterTest.java
Unit tests for initial implementation of Dingrogu build process using PNC build backend.
https://issues.redhat.com/browse/NCL-9004
=> NCL-9004 Update Orch to support PNC builds via Dingrogu (unit tests)

pom.xml, rest-workflow/pom.xml, rest-workflow/src/main/java/org/jboss/pnc/dingrogu/restworkflow/workflows/BuildWorkflow.java
We are running on class not found exception at runtime
=> Add javax.persistence just for PNC's artifact model

api/src/main/java/org/jboss/pnc/dingrogu/api/client/CausewayProducer.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/CausewayBuildPushAdapter.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/CausewayBuildPushAdapterTest.java
Had to create the CausewayProducer to properly inject mocks.
=> Add test for adapter CausewayBuildPushAdapter

rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/client/OrchClient.java
Maybe it's something we'll improve in the future
=> Use orch url without path for orch client

common/src/main/java/org/jboss/pnc/dingrogu/common/TaskHelper.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/ReqourAdjustAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/client/DeliverablesAnalyzerClient.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/client/DummyClient.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/client/GenericClient.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/client/OrchClient.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/client/RepositoryDriverClient.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/client/ReqourClient.java, rest-workflow/src/main/java/org/jboss/pnc/dingrogu/restworkflow/workflows/BuildWorkflow.java
=> Return a negative reqour error if response is empty

rest-workflow/src/main/java/org/jboss/pnc/dingrogu/restworkflow/workflows/BuildWorkflow.java
This otherwise causes issues with cancellations later.
=> Use provided correlation id for build workflow

rest-workflow/src/main/java/org/jboss/pnc/dingrogu/restworkflow/rest/WorkflowEndpointImpl.java
We need to tell Rex that the rollback succeeded for build env cleanup, otherwise we're stuck in the rollback process.
=> Tell Rex that the rollback succeeded

rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/RepositoryDriverSetupAdapter.java
This should fix TC53 for sbt alignment
=> Check if removedRepositories is not null from alignment

rest-workflow/src/main/java/org/jboss/pnc/dingrogu/restworkflow/workflows/BuildWorkflow.java
This takes into account the repo driver creation, and repo driver seal results
=> Improve completion status

rest-workflow/src/main/java/org/jboss/pnc/dingrogu/restworkflow/workflows/BuildWorkflow.java
Reverts project-ncl/dingrogu#175
=> Revert "[NCL-9145] Enable heartbeat on the graph request also"

pom.xml, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/Adapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/BuildDriverAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/CausewayBuildPushAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/DeliverablesAnalyzerAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/OrchBuildPushResultAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/RepositoryDriverPromoteAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/ReqourAdjustAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/ReqourCloneRepositoryAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/ReqourCreateRepositoryAdapter.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/BuildDriverAdapterTest.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/CausewayBuildPushAdapterTest.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/DeliverablesAnalyzerAdapterTest.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/RepositoryDriverPromoteAdapterTest.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/ReqourAdjustAdapterTest.java, rest-workflow/src/main/java/org/jboss/pnc/dingrogu/restworkflow/workflows/BuildWorkflow.java
Reverts project-ncl/dingrogu#174
=> Revert "[NCL-9145] Add heartbeat support"

pom.xml, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/Adapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/BuildDriverAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/CausewayBuildPushAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/DeliverablesAnalyzerAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/OrchBuildPushResultAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/RepositoryDriverPromoteAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/ReqourAdjustAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/ReqourCloneRepositoryAdapter.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/ReqourCreateRepositoryAdapter.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/BuildDriverAdapterTest.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/CausewayBuildPushAdapterTest.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/DeliverablesAnalyzerAdapterTest.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/RepositoryDriverPromoteAdapterTest.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/ReqourAdjustAdapterTest.java, rest-workflow/src/main/java/org/jboss/pnc/dingrogu/restworkflow/workflows/BuildWorkflow.java
Reverts project-ncl/dingrogu#181
=> Revert "Heartbeat again"

rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/RepositoryDriverPromoteAdapter.java
Only until proper heartbeat is implemented (NCL-9208).
=> [NCLSUP-1284] Do not use heartbeat for promotion temporarily

pom.xml, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/RepositoryDriverPromoteAdapter.java, rest-adapter/src/test/java/org/jboss/pnc/dingrogu/restadapter/adapter/RepositoryDriverPromoteAdapterTest.java
=> [NCLSUP-1284] Also comment out heartbeat config for request

api/src/main/java/org/jboss/pnc/dingrogu/api/dto/adapter/RepositoryDriverSetupDTO.java, api/src/main/java/org/jboss/pnc/dingrogu/api/dto/workflow/BuildWorkDTO.java, rest-adapter/src/main/java/org/jboss/pnc/dingrogu/restadapter/adapter/RepositoryDriverSetupAdapter.java
extra repositories was not passed in repo creation request
=> [NCLSUP-1288] Add missing parameter into repo setup request

rest-workflow/src/main/java/org/jboss/pnc/dingrogu/restworkflow/workflows/BuildWorkflow.java
This is directly connected to PNC's DatastoreAdapter `storeResult` method.
=> Deal better with failures by not setting builds to system-error

rest-workflow/src/main/java/org/jboss/pnc/dingrogu/restworkflow/workflows/BuildWorkflow.java
PNC-Orch wants DTO EnvironmentDriverResult, but the environment-driver service returns EnvironmentCreateResult.
The codebase wrongly assumed that the DTO returned by environment-driver was EnvironmentDriverResult.
This commit fixes this, and converts from EnvironmentCreateResult DTO to EnvironmentDriverResult.
=> [NCLSUP-1299] Grab correct DTO for EnvironmentDriverResult
